### ISSUE TITLE
Vanity tags for stable and mainline

### ISSUE THREAD

**Issue by jdolitsky** [distroless/nginx#28]
We should tag  1.22.0 as "stable" and 1.23.1 as "mainline" to better indicate why we support which versions of nginx

Related #27

**Comment by priyawadhwa** [comment]
I think this will just happen for `stable` once https://github.com/distroless/nginx/pull/27 is merged since I added the [additional tags](https://github.com/distroless/nginx/blob/main/.github/workflows/release.yaml#L96-L101) github action


Looks like we already have `mainline`:

```
 ~ % crane digest distroless.dev/nginx:mainline
sha256:2204bcbb106e6bb3ea8a9c1c9cf371f0583d15e2c2a8509b745c9c029b92d14d
 ~ % crane digest distroless.dev/nginx:1.23.1  
sha256:2204bcbb106e6bb3ea8a9c1c9cf371f0583d15e2c2a8509b745c9c029b92d14d
```

**Comment by jdolitsky** [comment]
👏
